// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGfMHccee2-2TIRg0P4UnaupR8P-71F0c',
    appId: '1:467306095090:web:a01ba21154115c64d2cb6b',
    messagingSenderId: '467306095090',
    projectId: 'unoweb-mp-discovery',
    authDomain: 'unoweb-mp-discovery.firebaseapp.com',
    storageBucket: 'unoweb-mp-discovery.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7avGC_BydKg5b-HbUyxCHibqZvRpfMR0',
    appId: '1:467306095090:android:3ecb561f9744f504d2cb6b',
    messagingSenderId: '467306095090',
    projectId: 'unoweb-mp-discovery',
    storageBucket: 'unoweb-mp-discovery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFdCNpgEvVi7keWc8UAzFWaO34eRMUe9c',
    appId: '1:467306095090:ios:89a60b37c10b3215d2cb6b',
    messagingSenderId: '467306095090',
    projectId: 'unoweb-mp-discovery',
    storageBucket: 'unoweb-mp-discovery.appspot.com',
    iosClientId: '467306095090-6dpe7uro5uq2jgbkno816h4hfc8noll1.apps.googleusercontent.com',
    iosBundleId: 'com.paytondeveloper.unoweb-flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFdCNpgEvVi7keWc8UAzFWaO34eRMUe9c',
    appId: '1:467306095090:ios:81172985a66bc804d2cb6b',
    messagingSenderId: '467306095090',
    projectId: 'unoweb-mp-discovery',
    storageBucket: 'unoweb-mp-discovery.appspot.com',
    iosClientId: '467306095090-ov798f6l4274fecs9qd4a2b5a813kn3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.unoweb',
  );
}
