// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw5sFj4L8QANPhEFmvfGr6OdsV1XnAfv4',
    appId: '1:734070076682:web:68ea14692e02adcbb536f3',
    messagingSenderId: '734070076682',
    projectId: 'justone-mp',
    authDomain: 'justone-mp.firebaseapp.com',
    storageBucket: 'justone-mp.appspot.com',
    measurementId: 'G-K878N99T26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxq2oyPzSGx16wyGLOu-zo9blkVcrS_Hk',
    appId: '1:734070076682:android:6291df785b853528b536f3',
    messagingSenderId: '734070076682',
    projectId: 'justone-mp',
    storageBucket: 'justone-mp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhTSggKY-JiVku3hBR6UgfHCBQpYxvp5g',
    appId: '1:734070076682:ios:3860f57b221241d9b536f3',
    messagingSenderId: '734070076682',
    projectId: 'justone-mp',
    storageBucket: 'justone-mp.appspot.com',
    iosClientId: '734070076682-un43dbtqvanjvavvpj7681b53mb89652.apps.googleusercontent.com',
    iosBundleId: 'com.paytondeveloper.justone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhTSggKY-JiVku3hBR6UgfHCBQpYxvp5g',
    appId: '1:734070076682:ios:3860f57b221241d9b536f3',
    messagingSenderId: '734070076682',
    projectId: 'justone-mp',
    storageBucket: 'justone-mp.appspot.com',
    iosClientId: '734070076682-un43dbtqvanjvavvpj7681b53mb89652.apps.googleusercontent.com',
    iosBundleId: 'com.paytondeveloper.justone',
  );
}
